version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ratemycampus
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
