version: 0.2

env:
  variables:
    CLIENT_DIR: "client"
    SERVER_DIR: "server"
    AWS_REGION: "ap-southeast-2"
    CLIENT_IMAGE: "ratemycampus-client"
    SERVER_IMAGE: "ratemycampus-server"
    DOCKERHUB_USERNAME: "habibqayoom6"
    DOCKERHUB_PASSWORD: "dckr_pat_KGwOT_G6WC5hT5uI-AJxN0PcUng"

phases:
  pre_build:
    commands:



      # Create client/.env file
      - echo Creating .env files...
      - echo "VITE_BACKEND_URL_PROD=http://localhost:8787/api/v1" > client/.env

      # Create server/.env file
      - echo Creating .env files...
      - echo 'DATABASE_URL="postgresql://user:password@db:5432/ratemycampus"' > server/.env
      - echo 'DIRECT_URL="postgresql://user:password@db:5432/ratemycampus"' >> server/.env
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 580420849247.dkr.ecr.$AWS_REGION.amazonaws.com

     
 


      - echo Logging in to DockerHub...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - echo Fetching DB secrets from SSM Parameter Store...
      - export DATABASE_URL=$(aws ssm get-parameter --name "/ratemycampus/DATABASE_URL" --with-decryption --region $AWS_REGION --query Parameter.Value --output text)
      - export DIRECT_URL=$(aws ssm get-parameter --name "/ratemycampus/DATABASE_URL" --with-decryption --region $AWS_REGION --query Parameter.Value --output text)

      - echo Getting Git commit hash for tagging...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building client Docker image...
      - docker build -t $CLIENT_IMAGE:$IMAGE_TAG ./$CLIENT_DIR

      - echo Building server Docker image with secrets...
      - docker build \
          --build-arg DATABASE_URL=$DATABASE_URL \
          --build-arg DIRECT_URL=$DATABASE_URL \
          -t $SERVER_IMAGE:$IMAGE_TAG ./$SERVER_DIR

  post_build:
    commands:
      - echo Tagging and pushing client image to ECR...
      - docker tag $CLIENT_IMAGE:$IMAGE_TAG 580420849247.dkr.ecr.$AWS_REGION.amazonaws.com/$CLIENT_IMAGE:$IMAGE_TAG
      - docker push 580420849247.dkr.ecr.$AWS_REGION.amazonaws.com/$CLIENT_IMAGE:$IMAGE_TAG

      - echo Tagging and pushing server image to ECR...
      - docker tag $SERVER_IMAGE:$IMAGE_TAG 580420849247.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVER_IMAGE:$IMAGE_TAG
      - docker push 580420849247.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVER_IMAGE:$IMAGE_TAG

artifacts:
  files: '**/*'
