version: 0.2

env:
  variables:
    CLIENT_DIR: "client"
    SERVER_DIR: "server"
    AWS_REGION: "xxxxx"
    CLIENT_IMAGE: "ratemycampus-client"
    SERVER_IMAGE: "ratemycampus-server"
    DOCKERHUB_USERNAME: "xxxxx"
    DOCKERHUB_PASSWORD: "xxxxx"

phases:
  pre_build:
    commands:

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin xxxxx.dkr.ecr.$AWS_REGION.amazonaws.com

      - echo Logging in to DockerHub...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - echo Getting Git commit hash for tagging...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building client Docker image...
      - docker build -t $CLIENT_IMAGE:$IMAGE_TAG ./$CLIENT_DIR

      - echo Building server Docker image...
      - docker build -t $SERVER_IMAGE:$IMAGE_TAG ./$SERVER_DIR

  post_build:
    commands:
      - echo Tagging and pushing client image to ECR...
      - docker tag $CLIENT_IMAGE:$IMAGE_TAG xxxxxx.dkr.ecr.$AWS_REGION.amazonaws.com/$CLIENT_IMAGE:$IMAGE_TAG
      - docker push 5xxxxx.dkr.ecr.$AWS_REGION.amazonaws.com/$CLIENT_IMAGE:$IMAGE_TAG

      - echo Tagging and pushing server image to ECR...
      - docker tag $SERVER_IMAGE:$IMAGE_TAG xxxxx.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVER_IMAGE:$IMAGE_TAG
      - docker push xxxxxxx.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVER_IMAGE:$IMAGE_TAG

artifacts:
  files: '**/*'
