version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ratemycampus
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
   
    volumes:
      - ./server:/app
    env_file: ./server/.env
    ports:
      - "8787:8787"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./client:/app
    env_file: ./client/.env
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db_data:
