version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ratemycampus
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    image: 580420849247.dkr.ecr.ap-southeast-2.amazonaws.com/ratemycampus-server:latest
   
    
    ports:
      - "8787:8787"
    depends_on:
      - db

  client:
    image: 580420849247.dkr.ecr.ap-southeast-2.amazonaws.com/ratemycampus-client:latest
    restart: on-failure
   
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db_data:
