name = "server"
compatibility_date = "2024-08-26"

[vars]
DATABASE_URL = "your_prisma_accelerate_connection_pooling_url"
DIRECT_URL = "your_direct_database_url"
R2_DEV = "your_cdn_link"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"

