name = "server"
compatibility_date = "2024-08-26"

[vars]
DATABASE_URL = "your_prisma_accelerate_connection_pooling_url"
DIRECT_URL = "your_direct_database_url"
R2_DEV = "your_cdn_link"
JWT_SECRET = "your_jwt_secret"
SUPER_USER = "you_email"

# [brevo]
BREVO_API = "your_brevo_api"
TEMPLATE_ID = "your_brevo_template_id"
VERIFICATION_ROUTE = "your_frontend_route_url_for_email_verification"
RESET_PASSWORD_ROUTE = "your_frontend_route_url_for_reset-password"
RESET_TEMPLATE = "your_brevo_reset-password_template_id"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"
